### ISSUE TITLE
Improvements needed

### ISSUE THREAD

**Issue by sashakames** [lisi-w/cic#1]
- The individual .json files should have filenames without spaces
- .json files have the filename prepended before the  .json output - eg: /p/user_pub/publish-queue/inconsistencies/210108_1601esgf.ichec.ie-Original record retracted:.jsonOriginal record retracted:[
- 400K+ no original record for esgf-data1 seems high.  The first record was correct  so not completely incorrect

**Comment by sashakames** [comment]
Additionally check if the automated retractions ran in the additional cases and the log, see /p/user_pub/publish-queue/inconsistencies

**Comment by sashakames** [comment]
Just noticed that took 8.5 hrs to run on greyworm.   Maybe that's the general case, but might be good to quantify the steps again and regularly to see if there are anomalies associated with problematic runs.

**Comment by sashakames** [comment]
CMIP-Table -based checks eg the activity_check, experiment_id  are slow
errata check performs a remote API for every dataset (Millions) so this is even slower 

- We should be able to disable these checks 
-  Also voluntarily take Institutions associated with an index node if we know the index node is offline. (Needed?)

**Comment by lisi-w** [comment]
Added ability to disable AC and Errata checking, will possibly add as command line options in the future
